name: BigQuery CICD Full Refresh
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from UI

jobs:
  dbt_run:
    name: dbt full refresh and test on BigQuery
    runs-on: ubuntu-latest

    env:
      # Environment variables
      PYTHON_VERSION: "3.10"
      DBT_PROJECT_DIR: "./integration_tests"
      DBT_CORE_VERSION: "1.10.15"
      # BigQuery connection variables
      DBT_BIGQUERY_CI_TOKEN: ${{ secrets.DBT_BIGQUERY_CI_TOKEN }}
      DBT_BIGQUERY_CI_PROJECT: ${{ secrets.DBT_BIGQUERY_CI_PROJECT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dbt-core and BigQuery adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==${{ env.DBT_CORE_VERSION }} dbt-bigquery
  
      - name: Create BigQuery credentials file
        run: |
          echo "${{ env.DBT_BIGQUERY_CI_TOKEN }}" | base64 --decode > ./creds.json
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Install dbt dependencies
        run: dbt deps --profiles-dir ./integration_tests/profiles/bigquery
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Test Connection
        run: dbt debug --profiles-dir ./integration_tests/profiles/bigquery
        working-directory: ${{ env.DBT_PROJECT_DIR }}

      - name: Build dbt models (full-refresh)
        run: |
          dbt build --full-refresh --profiles-dir ./integration_tests/profiles/bigquery
        working-directory: ${{ env.DBT_PROJECT_DIR }}